services:
  digitalwallets.api:
    image: ${DOCKER_REGISTRY-}digitalwalletsapi
    build:
      context: .
      dockerfile: DigitalWallets.API/Dockerfile
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pethelp_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: pethelp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: